### ISSUE TITLE
Case using STN

### ISSUE THREAD

**Issue by peternara** [wushilian/STN_CNN_LSTM_CTC_TensorFlow#1]
If STN is used, it does not converge.
Is there a good tip to converge?
and 
Have you tried evaluating IIIT5k dataset using the original CRNN without using STN? 
I implemented it with tf, but it did not perform like the paper.

**Comment by wushilian** [comment]
@peternara Maybe you can add more layeres in STN,I evaluated ICDAR2013,and it also didn't perform like the paper
